### ISSUE TITLE
Tweaks to your PredicIt script

### ISSUE THREAD

**Issue by nprto** [tuttlepower/predictit_markets#1]
Hi, I found your great script for scraping market histories from PredictIt, but got 403 errors when trying to access the data. I updated it to use requests instead of panda pd.read_csv, and made a few other tweaks. 

I updated it in my fork of your repository and I would be happy to make a pull request.

Thank you for sharing it.

**Comment by tuttlepower** [comment]
Sorry just saw this! I also realized it was pretty broken the other day and am updating it quite a bit

**Comment by tuttlepower** [comment]
https://pypi.org/project/predictit-markets/0.1.0/
Overkill, but I have set it to upload to PyPi now as well
